import { test, expect } from '@playwright/test';

// generated by playwright recorder. VSCode - Testing > under Playwright > Record new
// can do it in cmd: 
// npm playwright codegen https://duckduckgo.com
// then generated code will be in the Playwright Inspector instead of in VSCode

test('test', async ({ page }) => {
  await page.goto('https://duckduckgo.com/');
  await page.getByRole('combobox', { name: 'Search with DuckDuckGo' }).click();
  await page.getByRole('combobox', { name: 'Search with DuckDuckGo' }).fill('india');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
});